apiVersion: v1
kind: Service
metadata:
    name: "tipsandtricks-3280"
    labels:
        app: "tipsandtricks-3280"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "tipsandtricks-3280"